name: list-artifacts
on: [workflow_dispatch]
jobs:
  list-artifacts:
    runs-on: ubuntu-latest
    steps:
    - id: result 
      uses: MichaelMelena/list-artifacts@v1
    - run: echo '${{ steps.result.outputs.artifacts }}'
