name: upload

on: workflow_dispatch

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

    - uses: actions/checkout@v3

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@v1.1

    - uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: CMake
      run: |
        cmake -GNinja .

    - name: Build
      run: |
        ninja
    
    - name: Zip
      uses: vimtor/action-zip@v1
      with:
        dest: release-${{ runner.os }}.zip
        files: demumble demumble.exe

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: release-demumble
        path: release-${{ runner.os }}.zip
        if-no-files-found: error

  release:
    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p artifact/release

    - name: Download
      uses: actions/download-artifact@v3
      with:
        name: release-demumble
        path: artifact/release
    
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifact/release
